// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testfridge.proto

package io.grpc.smartkitchen.testfridge;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
