// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testphone.proto

package io.grpc.smartkitchen.testphone;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *setting number of responses we want returned from client
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   *setting number of responses we want returned from client
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
