// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package io.grpc.smartkitchen.phone;

public interface BoilRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BoilRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *setting number of responses we want returned from client
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   *setting number of responses we want returned from client
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
