// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package io.grpc.smartkitchen.phone;

public final class Phone {
  private Phone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BoilRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BoilRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BoilResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BoilResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PreheatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PreheatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PreheatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PreheatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TurnOffRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TurnOffRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TurnOffResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TurnOffResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightsOnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightsOnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightsOnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightsOnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightsOffRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightsOffRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightsOffResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightsOffResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013phone.proto\"\036\n\013BoilRequest\022\017\n\007message\030" +
      "\001 \001(\t\"9\n\014BoilResponse\022\023\n\013boilStarted\030\001 \001" +
      "(\t\022\024\n\014boilFinished\030\002 \001(\t\"%\n\022TemperatureR" +
      "equest\022\017\n\007message\030\001 \001(\t\"&\n\023TemperatureRe" +
      "sponse\022\017\n\007message\030\001 \001(\005\"/\n\016PreheatReques" +
      "t\022\017\n\007setting\030\001 \001(\t\022\014\n\004heat\030\002 \001(\005\"D\n\017Preh" +
      "eatResponse\022\033\n\023ovenSettingSelected\030\001 \001(\t" +
      "\022\024\n\014heatSelected\030\002 \001(\t\":\n\016TurnOffRequest" +
      "\022\023\n\013turnOffHeat\030\001 \001(\t\022\023\n\013turnOffOven\030\002 \001" +
      "(\t\"\"\n\017TurnOffResponse\022\017\n\007message\030\001 \001(\t\"\"" +
      "\n\017LightsOnRequest\022\017\n\007message\030\001 \001(\t\"#\n\020Li" +
      "ghtsOnResponse\022\017\n\007message\030\001 \001(\t\"#\n\020Light" +
      "sOffRequest\022\017\n\007message\030\001 \001(\t\"$\n\021LightsOf" +
      "fResponse\022\017\n\007message\030\001 \001(\t2\264\002\n\nSmartPhon" +
      "e\022%\n\004boil\022\014.BoilRequest\032\r.BoilResponse0\001" +
      "\0228\n\013temperature\022\023.TemperatureRequest\032\024.T" +
      "emperatureResponse\0220\n\007preheat\022\017.PreheatR" +
      "equest\032\020.PreheatResponse(\0010\001\022.\n\007turnOff\022" +
      "\017.TurnOffRequest\032\020.TurnOffResponse(\001\022/\n\010" +
      "lightsOn\022\020.LightsOnRequest\032\021.LightsOnRes" +
      "ponse\0222\n\tlightsOff\022\021.LightsOffRequest\032\022." +
      "LightsOffResponseB\036\n\032io.grpc.smartkitche" +
      "n.phoneP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BoilRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BoilRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BoilRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_BoilResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BoilResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BoilResponse_descriptor,
        new java.lang.String[] { "BoilStarted", "BoilFinished", });
    internal_static_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TemperatureRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TemperatureResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_PreheatRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PreheatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PreheatRequest_descriptor,
        new java.lang.String[] { "Setting", "Heat", });
    internal_static_PreheatResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PreheatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PreheatResponse_descriptor,
        new java.lang.String[] { "OvenSettingSelected", "HeatSelected", });
    internal_static_TurnOffRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_TurnOffRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TurnOffRequest_descriptor,
        new java.lang.String[] { "TurnOffHeat", "TurnOffOven", });
    internal_static_TurnOffResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_TurnOffResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TurnOffResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_LightsOnRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_LightsOnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightsOnRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_LightsOnResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_LightsOnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightsOnResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_LightsOffRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_LightsOffRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightsOffRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_LightsOffResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_LightsOffResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightsOffResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
