// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package io.grpc.smartkitchen.phone;

public interface PreheatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PreheatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ovenSettingSelected = 1;</code>
   */
  java.lang.String getOvenSettingSelected();
  /**
   * <code>string ovenSettingSelected = 1;</code>
   */
  com.google.protobuf.ByteString
      getOvenSettingSelectedBytes();

  /**
   * <code>string heatSelected = 2;</code>
   */
  java.lang.String getHeatSelected();
  /**
   * <code>string heatSelected = 2;</code>
   */
  com.google.protobuf.ByteString
      getHeatSelectedBytes();
}
