// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package io.grpc.smartkitchen.phone;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 message = 1;</code>
   */
  int getMessage();
}
