// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package io.grpc.smartkitchen.phone;

public interface TurnOffResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TurnOffResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
