// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oven.proto

package io.grpc.smartkitchen.oven;

public final class Oven {
  private Oven() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PreheatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PreheatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PreheatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PreheatResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TurnOffRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TurnOffRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TurnOffResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TurnOffResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\noven.proto\"/\n\016PreheatRequest\022\017\n\007settin" +
      "g\030\001 \001(\t\022\014\n\004heat\030\002 \001(\005\"D\n\017PreheatResponse" +
      "\022\033\n\023ovenSettingSelected\030\001 \001(\t\022\024\n\014heatSel" +
      "ected\030\002 \001(\t\":\n\016TurnOffRequest\022\023\n\013turnOff" +
      "Heat\030\001 \001(\t\022\023\n\013turnOffOven\030\002 \001(\t\"\"\n\017TurnO" +
      "ffResponse\022\017\n\007message\030\001 \001(\t2m\n\tSmartOven" +
      "\0220\n\007preheat\022\017.PreheatRequest\032\020.PreheatRe" +
      "sponse(\0010\001\022.\n\007turnOff\022\017.TurnOffRequest\032\020" +
      ".TurnOffResponse(\001B\035\n\031io.grpc.smartkitch" +
      "en.ovenP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PreheatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PreheatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PreheatRequest_descriptor,
        new java.lang.String[] { "Setting", "Heat", });
    internal_static_PreheatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PreheatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PreheatResponse_descriptor,
        new java.lang.String[] { "OvenSettingSelected", "HeatSelected", });
    internal_static_TurnOffRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_TurnOffRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TurnOffRequest_descriptor,
        new java.lang.String[] { "TurnOffHeat", "TurnOffOven", });
    internal_static_TurnOffResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TurnOffResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TurnOffResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
