// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oven.proto

package io.grpc.smartkitchen.oven;

public interface PreheatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PreheatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *setting number of responses we want returned from client
   * </pre>
   *
   * <code>string setting = 1;</code>
   */
  java.lang.String getSetting();
  /**
   * <pre>
   *setting number of responses we want returned from client
   * </pre>
   *
   * <code>string setting = 1;</code>
   */
  com.google.protobuf.ByteString
      getSettingBytes();

  /**
   * <code>int32 heat = 2;</code>
   */
  int getHeat();
}
