// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: oven.proto

package io.grpc.smartkitchen.oven;

public interface TurnOffRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TurnOffRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string turnOffHeat = 1;</code>
   */
  java.lang.String getTurnOffHeat();
  /**
   * <code>string turnOffHeat = 1;</code>
   */
  com.google.protobuf.ByteString
      getTurnOffHeatBytes();

  /**
   * <code>string turnOffOven = 2;</code>
   */
  java.lang.String getTurnOffOven();
  /**
   * <code>string turnOffOven = 2;</code>
   */
  com.google.protobuf.ByteString
      getTurnOffOvenBytes();
}
