// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kettle.proto

package io.grpc.smartkitchen.kettle;

/**
 * Protobuf type {@code BoilResponse}
 */
public  final class BoilResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:BoilResponse)
    BoilResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BoilResponse.newBuilder() to construct.
  private BoilResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BoilResponse() {
    boilStarted_ = "";
    boilFinished_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BoilResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            boilStarted_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            boilFinished_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.smartkitchen.kettle.Kettle.internal_static_BoilResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.smartkitchen.kettle.Kettle.internal_static_BoilResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.smartkitchen.kettle.BoilResponse.class, io.grpc.smartkitchen.kettle.BoilResponse.Builder.class);
  }

  public static final int BOILSTARTED_FIELD_NUMBER = 1;
  private volatile java.lang.Object boilStarted_;
  /**
   * <code>string boilStarted = 1;</code>
   */
  public java.lang.String getBoilStarted() {
    java.lang.Object ref = boilStarted_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      boilStarted_ = s;
      return s;
    }
  }
  /**
   * <code>string boilStarted = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBoilStartedBytes() {
    java.lang.Object ref = boilStarted_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      boilStarted_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BOILFINISHED_FIELD_NUMBER = 2;
  private volatile java.lang.Object boilFinished_;
  /**
   * <code>string boilFinished = 2;</code>
   */
  public java.lang.String getBoilFinished() {
    java.lang.Object ref = boilFinished_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      boilFinished_ = s;
      return s;
    }
  }
  /**
   * <code>string boilFinished = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBoilFinishedBytes() {
    java.lang.Object ref = boilFinished_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      boilFinished_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBoilStartedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, boilStarted_);
    }
    if (!getBoilFinishedBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, boilFinished_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBoilStartedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, boilStarted_);
    }
    if (!getBoilFinishedBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, boilFinished_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.smartkitchen.kettle.BoilResponse)) {
      return super.equals(obj);
    }
    io.grpc.smartkitchen.kettle.BoilResponse other = (io.grpc.smartkitchen.kettle.BoilResponse) obj;

    boolean result = true;
    result = result && getBoilStarted()
        .equals(other.getBoilStarted());
    result = result && getBoilFinished()
        .equals(other.getBoilFinished());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOILSTARTED_FIELD_NUMBER;
    hash = (53 * hash) + getBoilStarted().hashCode();
    hash = (37 * hash) + BOILFINISHED_FIELD_NUMBER;
    hash = (53 * hash) + getBoilFinished().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.smartkitchen.kettle.BoilResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.smartkitchen.kettle.BoilResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.smartkitchen.kettle.BoilResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.smartkitchen.kettle.BoilResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.smartkitchen.kettle.BoilResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.smartkitchen.kettle.BoilResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.smartkitchen.kettle.BoilResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.smartkitchen.kettle.BoilResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.smartkitchen.kettle.BoilResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.smartkitchen.kettle.BoilResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.smartkitchen.kettle.BoilResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.smartkitchen.kettle.BoilResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.smartkitchen.kettle.BoilResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code BoilResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:BoilResponse)
      io.grpc.smartkitchen.kettle.BoilResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.smartkitchen.kettle.Kettle.internal_static_BoilResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.smartkitchen.kettle.Kettle.internal_static_BoilResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.smartkitchen.kettle.BoilResponse.class, io.grpc.smartkitchen.kettle.BoilResponse.Builder.class);
    }

    // Construct using io.grpc.smartkitchen.kettle.BoilResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      boilStarted_ = "";

      boilFinished_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.smartkitchen.kettle.Kettle.internal_static_BoilResponse_descriptor;
    }

    @java.lang.Override
    public io.grpc.smartkitchen.kettle.BoilResponse getDefaultInstanceForType() {
      return io.grpc.smartkitchen.kettle.BoilResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.grpc.smartkitchen.kettle.BoilResponse build() {
      io.grpc.smartkitchen.kettle.BoilResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.grpc.smartkitchen.kettle.BoilResponse buildPartial() {
      io.grpc.smartkitchen.kettle.BoilResponse result = new io.grpc.smartkitchen.kettle.BoilResponse(this);
      result.boilStarted_ = boilStarted_;
      result.boilFinished_ = boilFinished_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.smartkitchen.kettle.BoilResponse) {
        return mergeFrom((io.grpc.smartkitchen.kettle.BoilResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.smartkitchen.kettle.BoilResponse other) {
      if (other == io.grpc.smartkitchen.kettle.BoilResponse.getDefaultInstance()) return this;
      if (!other.getBoilStarted().isEmpty()) {
        boilStarted_ = other.boilStarted_;
        onChanged();
      }
      if (!other.getBoilFinished().isEmpty()) {
        boilFinished_ = other.boilFinished_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.smartkitchen.kettle.BoilResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.smartkitchen.kettle.BoilResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object boilStarted_ = "";
    /**
     * <code>string boilStarted = 1;</code>
     */
    public java.lang.String getBoilStarted() {
      java.lang.Object ref = boilStarted_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        boilStarted_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string boilStarted = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBoilStartedBytes() {
      java.lang.Object ref = boilStarted_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        boilStarted_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string boilStarted = 1;</code>
     */
    public Builder setBoilStarted(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      boilStarted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string boilStarted = 1;</code>
     */
    public Builder clearBoilStarted() {
      
      boilStarted_ = getDefaultInstance().getBoilStarted();
      onChanged();
      return this;
    }
    /**
     * <code>string boilStarted = 1;</code>
     */
    public Builder setBoilStartedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      boilStarted_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object boilFinished_ = "";
    /**
     * <code>string boilFinished = 2;</code>
     */
    public java.lang.String getBoilFinished() {
      java.lang.Object ref = boilFinished_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        boilFinished_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string boilFinished = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBoilFinishedBytes() {
      java.lang.Object ref = boilFinished_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        boilFinished_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string boilFinished = 2;</code>
     */
    public Builder setBoilFinished(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      boilFinished_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string boilFinished = 2;</code>
     */
    public Builder clearBoilFinished() {
      
      boilFinished_ = getDefaultInstance().getBoilFinished();
      onChanged();
      return this;
    }
    /**
     * <code>string boilFinished = 2;</code>
     */
    public Builder setBoilFinishedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      boilFinished_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:BoilResponse)
  }

  // @@protoc_insertion_point(class_scope:BoilResponse)
  private static final io.grpc.smartkitchen.kettle.BoilResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.smartkitchen.kettle.BoilResponse();
  }

  public static io.grpc.smartkitchen.kettle.BoilResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BoilResponse>
      PARSER = new com.google.protobuf.AbstractParser<BoilResponse>() {
    @java.lang.Override
    public BoilResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BoilResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BoilResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BoilResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.grpc.smartkitchen.kettle.BoilResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

