// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kettle.proto

package io.grpc.smartkitchen.kettle;

public interface BoilResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BoilResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string boilStarted = 1;</code>
   */
  java.lang.String getBoilStarted();
  /**
   * <code>string boilStarted = 1;</code>
   */
  com.google.protobuf.ByteString
      getBoilStartedBytes();

  /**
   * <code>string boilFinished = 2;</code>
   */
  java.lang.String getBoilFinished();
  /**
   * <code>string boilFinished = 2;</code>
   */
  com.google.protobuf.ByteString
      getBoilFinishedBytes();
}
