// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kettle.proto

package io.grpc.smartkitchen.kettle;

public final class Kettle {
  private Kettle() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BoilRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BoilRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BoilResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BoilResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014kettle.proto\"\036\n\013BoilRequest\022\017\n\007message" +
      "\030\001 \001(\t\"9\n\014BoilResponse\022\023\n\013boilStarted\030\001 " +
      "\001(\t\022\024\n\014boilFinished\030\002 \001(\t24\n\013SmartKettle" +
      "\022%\n\004boil\022\014.BoilRequest\032\r.BoilResponse0\001B" +
      "\037\n\033io.grpc.smartkitchen.kettleP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BoilRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BoilRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BoilRequest_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_BoilResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BoilResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BoilResponse_descriptor,
        new java.lang.String[] { "BoilStarted", "BoilFinished", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
